package ch.innovazion.glom;

import com.jogamp.opengl.GL4;

public enum BufferType {
	ARRAY(GL4.GL_ARRAY_BUFFER),
	ATOMIC_COUNTER(GL4.GL_ATOMIC_COUNTER_BUFFER),
	COPY_READ(GL4.GL_COPY_READ_BUFFER),
	COPY_WRITE(GL4.GL_COPY_WRITE_BUFFER),
	DISPATCH_INDIRECT(GL4.GL_DISPATCH_INDIRECT_BUFFER),
	DRAW_INDIRECT(GL4.GL_DRAW_INDIRECT_BUFFER),
	ELEMENT_ARRAY(GL4.GL_ELEMENT_ARRAY_BUFFER),
	PIXEL_PACK(GL4.GL_PIXEL_PACK_BUFFER),
	PIXEL_UNPACK(GL4.GL_PIXEL_UNPACK_BUFFER),
	QUERY(GL4.GL_QUERY_BUFFER),
	SHADER_STORAGE(GL4.GL_SHADER_STORAGE_BUFFER),
	TEXTURE(GL4.GL_TEXTURE_BUFFER),
	TRANSFORM_FEEDBACK(GL4.GL_TRANSFORM_FEEDBACK_BUFFER),
	UNIFORM(GL4.GL_UNIFORM_BUFFER);
	
	private final int type;
	
	BufferType(int type) {
		this.type = type;
	}
	
	public int getGLType() {
		return type;
	}
}
